name = "cineflue084"
account_id = "46f7bef008a04d13a6bd134c3a291006"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SITE_URL = "https://cineflue084.sk6216071.workers.dev"
NEXT_PUBLIC_TMDB_API_KEY = "8265bd1679663a7ea12ac168da84d2e8"
APP_ENV = "production"
CINEFUEL_ENV = "production"
WORKER_NAME = "cineflue084"
