name = "cinephile"
account_id = "46f7bef008a04d13a6bd134c3a291006"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SITE_URL = "https://cinephile.sk6216071.workers.dev"
NEXT_PUBLIC_TMDB_API_KEY = "8265bd1679663a7ea12ac168da84d2e8"
APP_ENV = "production"
CINEFUEL_ENV = "production"
WORKER_NAME = "cinephile"
MONGODB_URI = "mongodb+srv://shyam:shyam081@cluster0.fiwla4n.mongodb.net/?retryWrites=true&w=majority"
MONGODB_DATABASE = "cinefuel"
UPSTASH_REDIS_REST_URL = "https://nearby-wren-184114.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "gQAAAAAAAs8yAAIgcDJjOWYwZjkyNzlhNmQ0NTk2YTE2ZTAwNGFhODA0NGIxYg"
TELEGRAM_BOT_TOKEN = "8944564119:AAFvosKNpP5ffYKb5tWBl18CFCuqI0EmOzA"
TELEGRAM_BOT_USERNAME = "CineFlue_bot"
ADMIN_USER = "shyam"
ADMIN_PASSWORD = "Shyam081"
ADMIN_SECRET_KEY = "Shyam081"
ADMIN_SESSION_SECRET = "cinephile_session_secret_shyam_2026"
