'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { Sparkles, Star, ArrowRight, Compass, Flame, Film, Bookmark, Plus, Check } from 'lucide-react';
import { useWatchlist } from '@/context/WatchlistContext';
import { getPersonalizedRecommendations, PersonalizedRecommendationsResult } from '@/lib/recommendations';
import { getImageURL } from '@/lib/tmdb';
import MovieCard from './MovieCard';

export const PersonalizedRecommendations: React.FC = () => {
  const { watchlist, isMounted } = useWatchlist();
  const [data, setData] = useState<PersonalizedRecommendationsResult | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let isCancelled = false;

    async function loadRecommendations() {
      setLoading(true);
      try {
        const res = await getPersonalizedRecommendations(watchlist);
        if (!isCancelled) {
          setData(res);
        }
      } catch (err) {
        console.error('Error generating recommendations:', err);
      } finally {
        if (!isCancelled) setLoading(false);
      }
    }

    if (isMounted) {
      loadRecommendations();
    }

    return () => {
      isCancelled = true;
    };
  }, [watchlist, isMounted]);

  if (!isMounted || loading || !data || data.forYou.length === 0) {
    return null;
  }

  return (
    <section className="py-8 sm:py-10 bg-gradient-to-b from-amber-500/5 via-transparent to-transparent border-y border-amber-500/10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        {/* Header */}
        <div className="flex items-end justify-between">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-xs font-bold text-amber-400 uppercase tracking-wider">
              <Sparkles className="w-4 h-4" /> Recommended Just For You
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
              Personalized Discovery Feed
            </h2>
            <p className="text-xs sm:text-sm text-zinc-400">
              Generated by CineFuel&apos;s AI algorithm analyzing your watched titles, 1-10 star scores, and favorite genres.
            </p>
          </div>

          <Link
            href="/recommendations"
            className="hidden sm:flex items-center gap-1 text-xs font-bold text-amber-400 hover:text-amber-300 transition-colors"
          >
            Explore All Picks <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        {/* Featured Recommendation Cards with Reason Badges */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
          {data.forYou.slice(0, 4).map((rec, idx) => {
            const item = rec.item;
            const posterUrl = getImageURL(item.poster_path, 'w500');
            const mediaType = item.media_type || (item.name ? 'tv' : 'movie');
            const title = item.title || item.name || 'Untitled';
            const year = (item.release_date || item.first_air_date || '').split('-')[0];

            return (
              <div
                key={`rec-${item.id}-${idx}`}
                className="group relative flex flex-col rounded-2xl bg-[#11141c] border border-amber-500/20 overflow-hidden hover:border-amber-400 hover:shadow-2xl hover:shadow-amber-500/15 transition-all duration-300"
              >
                {/* Reason Pill Header */}
                <div className="px-3.5 py-2 bg-gradient-to-r from-amber-500/20 to-orange-500/10 border-b border-amber-500/20 flex items-center gap-1.5 text-[11px] font-bold text-amber-300 truncate">
                  <Sparkles className="w-3 h-3 text-amber-400 shrink-0" />
                  <span className="truncate">{rec.reason}</span>
                </div>

                {/* Poster Link */}
                <Link
                  href={`/${mediaType}/${item.id}`}
                  className="relative aspect-[16/10] w-full overflow-hidden bg-zinc-900 block"
                >
                  <Image
                    src={posterUrl}
                    alt={title}
                    fill
                    sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw"
                    className="object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent" />

                  {item.vote_average > 0 && (
                    <div className="absolute top-2.5 right-2.5 flex items-center gap-1 px-2 py-0.5 rounded-md bg-black/80 backdrop-blur-md text-xs font-bold text-amber-300 border border-amber-400/30">
                      <Star className="w-3 h-3 fill-amber-400 text-amber-400" />
                      <span>{item.vote_average.toFixed(1)}</span>
                    </div>
                  )}

                  <div className="absolute bottom-2.5 left-3 right-3">
                    <h3 className="text-sm font-bold text-white line-clamp-1 group-hover:text-amber-400 transition-colors">
                      {title}
                    </h3>
                    <div className="flex items-center gap-2 text-[11px] text-zinc-400 mt-0.5">
                      <span>{year}</span>
                      {item.genres && item.genres.length > 0 && (
                        <span>• {item.genres.slice(0, 2).map((g) => g.name).join(', ')}</span>
                      )}
                    </div>
                  </div>
                </Link>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default PersonalizedRecommendations;
